//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardioCarta.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CardioCartaEntities : DbContext
    {
        public CardioCartaEntities()
            : base("name=CardioCartaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Airly> Airly { get; set; }
        public virtual DbSet<AirlyForecast> AirlyForecast { get; set; }
        public virtual DbSet<BiometeoCurrent> BiometeoCurrent { get; set; }
        public virtual DbSet<BiometeoForecast> BiometeoForecast { get; set; }
        public virtual DbSet<Diary> Diary { get; set; }
        public virtual DbSet<Disease> Disease { get; set; }
        public virtual DbSet<Doctor> Doctor { get; set; }
        public virtual DbSet<Medicine> Medicine { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<PatientInterview> PatientInterview { get; set; }
        public virtual DbSet<PatientMedicine> PatientMedicine { get; set; }
        public virtual DbSet<spatial_ref_sys> spatial_ref_sys { get; set; }
        public virtual DbSet<Speciality> Speciality { get; set; }
        public virtual DbSet<TakenMedicine> TakenMedicine { get; set; }
        public virtual DbSet<TakingMedicineTime> TakingMedicineTime { get; set; }
    }
}
