//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardioCarta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientMedicine
    {
        public string Id { get; set; }
        public string Patient_AspNetUsers_Id { get; set; }
        public string Medicine_Name { get; set; }
        public int MgDose { get; set; }
        public string TakingTime { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual TakingMedicineTime TakingMedicineTime { get; set; }
    }
}
