//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardioCarta.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PatientInterview
    {
        public string Patient_AspNetUsers_Id { get; set; }

        [Display(Name = "Ostatnio mierzone ciœnienie rozkurczowe")]
        [Range(0, 300)]
        public Nullable<int> DiastolicPressure { get; set; }

        [Display(Name = "Ostatnio mierzone ciœnienie skurczowe")]
        [Range(0, 300)]
        public Nullable<int> SystolicPressure { get; set; }

        [Display(Name = "Czy przechodzi³(a) Pan(i) operacje?")]
        public bool Surgery { get; set; }

        [Display(Name = "Czy w Pani/Pana rodzinie wystêpuj¹ choroby kardiologiczne?")]
        public bool DiseaseInFamily { get; set; }

        [Display(Name = "Czy jest Pan(i) uzale¿niony/a od tytoniu?")]
        public bool Smoking { get; set; }
        [Range(1, 10)]

        [Display(Name = "Jak ocenia Pan(i) swoje zrowie w skali od 1-bardzo s³abe do 10-bardzo dobre")]
        public int Health { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
